### ISSUE TITLE
feature file resolution does not work on windows machines

### ISSUE THREAD

**Issue by pfried** [NordicSemiconductor/cloud-e2e-bdd-test-runner-js#601]
There is an issue where the feature runner cannot resolve the `*.feature` files on a windows machine

`const scan = path.join(path.resolve(dir), '*.feature');`

`path.resolve` will return a platform dependent path on windows something like `C:\Users\maeckle` but glob [only works with forward slashes ](https://github.com/isaacs/node-glob/issues/212)

I would have loved just changing the API to pass the whole glob pattern (that would also allow subdirectories **/*.feature) or different filenames, but that would be a breaking change. I will think about how to solve it, maybe something like [this](https://github.com/GoogleChrome/lighthouse/pull/9406#issuecomment-513019171).

**Comment by coderbyheart** [comment]
Thanks for reporting, please not that we do not support Windows right now. [We recommend to use WSL 2 if you must use Windows.](https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/saga/docs/project/SystemRequirements.html)

That said, could you try the fix from #602? It might solve your problem.

**Comment by pfried** [comment]
yeah that fix works, next issue upcoming tough #603

thanks for the fix
